name: Create an issue
description: Create an issue to start working on your script
title: "[Issue title here] "
body:
  - type: markdown
    attributes:
      value: |
        Create an issue to start working on your project
  - type: checkboxes #prerequisites
    attributes:
        label: Prerequisites
        description: Please answer the following questions for yourself before submitting an issue. 
        options:
        - label: I am a HSOC-22 Participant
          required: true
        - label: I checked to make sure that this issue has not already been filed
          required: true
  - type: textarea #description
    attributes:
        label: Description
        description: Tell us about this issue
        placeholder: Describe here!
    validations:
         required: true
  - type: textarea #screenshots
    attributes:
        label: Screenshots
        description: Please attach any screenshots for better reference
        placeholder: Describe here!
  - type: checkboxes #terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Rakesh9100/InstaStore/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I follow [Contributing Guidelines](https://github.com/Rakesh9100/InstaStore/blob/master/.github/CONTRIBUTING_GUIDELINES.md) of this project.
          required: true
  